
[server]
bind_addr = "127.0.0.1:1080"
max_connections = 1000
connection_timeout = "5m"
buffer_size = 8192
shutdown_timeout = "30s"
idle_timeout = "1m"
handshake_timeout = "10s"
max_memory_mb = 512
connection_pool_size = 10
enable_keepalive = true
keepalive_interval = "30s"

[auth]
enabled = true
method = "userpass"

[[auth.users]]
username = "demo_user"
password = "demo_pass"
enabled = true

[[auth.users]]
username = "test_user"
password = "test_pass"
enabled = true

[access_control]
enabled = false
default_policy = "allow"
rules = []

[routing]
enabled = false
upstream_proxies = []
rules = []

[routing.smart_routing]
enabled = false
health_check_interval = "30s"
health_check_timeout = "5s"
min_measurements = 3
enable_latency_routing = true
enable_health_routing = true

[monitoring]
enabled = true
metrics_addr = "127.0.0.1:9090"
log_level = "info"
prometheus_enabled = true
collect_connection_stats = true
max_historical_connections = 10000

[monitoring.management_api]
enabled = true
bind_addr = "127.0.0.1:8080"

[monitoring.management_api.auth]
enabled = true
api_key = "demo-api-key"

[security]
rate_limiting_enabled = true
max_requests_per_minute = 60
ddos_protection_enabled = true
connection_flood_threshold = 100
fail2ban_enabled = true
max_failed_attempts = 5
ban_duration = "1h"
secrets_encryption_enabled = false
