# Test Configuration for SOCKS5 Proxy Server

[server]
bind_addr = "127.0.0.1:1080"
max_connections = 100
connection_timeout = "30s"
handshake_timeout = "10s"
idle_timeout = "300s"
shutdown_timeout = "30s"
buffer_size = 8192
max_memory_mb = 256
connection_pool_size = 10
enable_keepalive = true
keepalive_interval = "30s"

[auth]
enabled = true
method = "userpass"

[[auth.users]]
username = "testuser"
password = "testpass"
enabled = true

[[auth.users]]
username = "admin"
password = "adminpass"
enabled = true

[access_control]
enabled = true
default_policy = "allow"

[[access_control.rules]]
pattern = "*.example.com"
action = "block"
reason = "Blocked domain for testing"

[[access_control.rules]]
pattern = "127.0.0.1"
action = "allow"
reason = "Local connections allowed"

[routing]
enabled = true
upstream_proxies = []
rules = []

[routing.smart_routing]
enabled = false
health_check_interval = "30s"
health_check_timeout = "5s"
min_measurements = 3
enable_latency_routing = true
enable_health_routing = true

[security.rate_limiting]
enabled = true
connections_per_ip_per_minute = 60
connections_per_ip_burst = 10
auth_attempts_per_ip_per_minute = 10
auth_attempts_per_ip_burst = 3
global_connections_per_second = 1000
cleanup_interval_seconds = 300
block_duration_minutes = 15

[security.ddos_protection]
enabled = true
connection_threshold = 50
time_window_seconds = 60
block_duration_minutes = 30
max_connections_per_ip = 10
global_connection_threshold = 5000
enable_progressive_delays = true
base_delay_ms = 100
max_delay_ms = 5000
cleanup_interval_seconds = 300

[security.fail2ban]
enabled = true
max_auth_failures = 5
failure_window_minutes = 10
ban_duration_minutes = 30
progressive_ban_multiplier = 2.0
max_ban_duration_hours = 24
enable_progressive_delays = true
base_delay_ms = 1000
max_delay_ms = 30000
whitelist_ips = ["127.0.0.1"]
cleanup_interval_seconds = 300

[security.secrets]
encrypt_config = false
use_env_secrets = true
secret_key_env = "SOCKS5_SECRET_KEY"
config_encryption_key_env = "SOCKS5_CONFIG_KEY"

[monitoring]
enabled = true
metrics_addr = "127.0.0.1:9090"
log_level = "info"
prometheus_enabled = true
collect_connection_stats = true
max_historical_connections = 1000

[monitoring.management_api]
enabled = false
bind_addr = "127.0.0.1:8080"

[monitoring.management_api.auth]
enabled = false